import { useEffect, useState } from "react";
import { ApiError, apiGet, apiMessage, apiSend } from "../api";
import { PageHeader } from "../components/kit";
import { TEMPLATE, TEMPLATE_NAME } from "../data";

interface TokenRow {
  id: string;
  name: string;
  createdAt: string;
}

/** Agency-wide settings: which template is running, how the dashboard reaches the platform, plus
 * MCP token minting — which the deployment does not offer. Minting is unauthenticated, so
 * on a public URL it would hand any visitor this agency's tools; the deployed
 * server answers 404 there and the platform's own injected token does the job. */
export function Settings() {
  const [tokens, setTokens] = useState<TokenRow[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  /** Set when the server says the token routes are not here — the deployed case, not a failure. */
  const [managed, setManaged] = useState(false);
  const [name, setName] = useState("");
  /** The plaintext of the last minted token — shown once, never refetchable. */
  const [minted, setMinted] = useState<{ name: string; token: string } | null>(null);

  useEffect(() => {
    void apiGet<TokenRow[]>("/mcp/tokens")
      .then(setTokens)
      .catch((err: unknown) => {
        if (err instanceof ApiError && err.status === 404) return setManaged(true);
        setError(apiMessage(err));
      });
  }, []);

  const mint = async () => {
    try {
      const created = await apiSend<TokenRow & { token: string }>("POST", "/mcp/tokens", { name: name.trim() });
      setMinted({ name: created.name, token: created.token });
      setTokens((rows) => [...(rows ?? []), { id: created.id, name: created.name, createdAt: created.createdAt }]);
      setName("");
    } catch (err: unknown) {
      setError(apiMessage(err));
    }
  };

  const revoke = async (id: string) => {
    try {
      await apiSend("DELETE", `/mcp/tokens/${id}`);
      setTokens((rows) => (rows ?? []).filter((t) => t.id !== id));
    } catch (err: unknown) {
      setError(apiMessage(err));
    }
  };

  return (
    <div className="pane-in">
      <PageHeader
        title="Settings"
        subtitle="How this dashboard talks to your platform organization."
        actions={error ? <span className="text-xs text-fail">{error}</span> : null}
      />

      <div className="list max-w-xl">
        {/*
          Which template this dashboard is running, and how to change it — not a switcher. A
          template is data compiled into this app and its config: switching means editing
          `templates/index.ts` and running `naive up`, which widens the org (new agents created,
          old ones left standing) and rebuilds the app. A control here would have to pretend it
          could do that from the browser, and it cannot.
        */}
        <div className="px-3 py-2.5">
          <div className="font-medium">
            Template <span className="chip chip-plain font-mono">{TEMPLATE_NAME}</span>
          </div>
          <p className="mt-0.5 text-xs text-ink-2">
            {TEMPLATE.description} It files{" "}
            {TEMPLATE.kinds.map((k) => k.label.toLowerCase()).join(", ")}. To switch, edit{" "}
            <span className="font-mono">TEMPLATE</span> in <span className="font-mono">templates/index.ts</span> and run{" "}
            <span className="font-mono">naive up</span>. Switching only widens: agents the new template declares are
            created, agents only the old one declared are reported and left alone, and your clients, deliverables and
            connections are untouched.
          </p>
        </div>
        <div className="px-3 py-2.5">
          <div className="font-medium">Platform API key</div>
          <p className="mt-0.5 text-xs text-ink-2">
            The deployment reads <span className="font-mono">NAIVE_API_KEY</span> from the app's environment, declared in
            <span className="font-mono"> naive.config.ts</span>; locally, set it before <span className="font-mono">pnpm serve</span>.
            The key never reaches the browser — screens go through <span className="font-mono">/api/*</span>. Without it the CRM
            and the content queue still work, and anything that needs the platform says so where you asked for it.
          </p>
        </div>
        <div className="px-3 py-2.5">
          <div className="font-medium">Dashboard access token</div>
          <p className="mt-0.5 text-xs text-ink-2">
            Every <span className="font-mono">/api/*</span> route requires the app's
            <span className="font-mono"> DASHBOARD_TOKEN</span>, declared in <span className="font-mono">naive.config.ts</span> and
            generated by you. This tab asks for it once and keeps it until the tab closes — it is never written to a URL or a
            log. Rotate it by exporting a new value and re-deploying; the next page load asks again.
          </p>
        </div>
        <div className="px-3 py-2.5">
          <div className="font-medium">Client identities</div>
          <p className="mt-0.5 text-xs text-ink-2">
            Each client gets one platform identity at onboarding; its connections live on the client's Connections tab.
          </p>
        </div>
        <div className="px-3 py-2.5">
          <div className="font-medium">MCP access</div>
          {managed ? (
            <p className="mt-0.5 text-xs text-ink-2">
              This app's MCP token is managed by the platform: it was minted for you at deploy time and injected into the app,
              so every agent in this project already reaches <span className="font-mono">POST /mcp</span>. Tokens for outside
              clients are minted from a local <span className="font-mono">pnpm serve</span>.
            </p>
          ) : (
            <>
              <p className="mt-0.5 text-xs text-ink-2">
                Outside agents operate this agency through <span className="font-mono">POST /mcp</span> with a bearer token
                minted here. Tokens are stored hashed; the platform API key is never an MCP credential.
              </p>
              <div className="mt-2 flex gap-2">
                <input
                  className="input flex-1"
                  placeholder="Token name (e.g. desktop client)"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                />
                <button type="button" className="btn btn-primary btn-sm" disabled={name.trim() === ""} onClick={() => void mint()}>
                  Mint token
                </button>
              </div>
              {minted ? (
                <p className="mt-2 text-xs text-ink-2">
                  Token for <span className="font-medium">{minted.name}</span> — copy it now, it is shown only once:
                  <span className="mt-1 block break-all font-mono">{minted.token}</span>
                </p>
              ) : null}
              {tokens !== null && tokens.length > 0 ? (
                <div className="mt-2 space-y-1">
                  {tokens.map((t) => (
                    <div key={t.id} className="flex items-center justify-between gap-2 text-xs">
                      <span className="font-medium">{t.name}</span>
                      <span className="text-ink-3">{new Date(t.createdAt).toLocaleDateString()}</span>
                      <button type="button" className="btn btn-ghost btn-sm" onClick={() => void revoke(t.id)}>Revoke</button>
                    </div>
                  ))}
                </div>
              ) : null}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
