/**
 * Every route this dashboard answers, in one table over one store (ADR-0374).
 *
 * `server/index.ts` (node `http`, `pnpm serve`) and `server/api-entry.ts` (the deployed function)
 * are thin adapters: each builds an `ApiRequest`, calls `handleRequest`, and writes the `ApiReply`.
 * Neither holds a route, so `/mcp` and `/api/*` are the same rows of the same document by
 * construction — an agent's CRM write is what the UI reads back.
 *
 * Nothing here touches a socket, a file or a database: the store arrives through `ctx.store()`,
 * which the entry opens lazily, so the platform-only routes cost no connection at all.
 */
import { authorized, bearerOf, handleMcp, mintToken, sameSecret, ticketMatches } from "./mcp.ts";
import { collect, latestContext, listAgents, provisionClientAgents, proxyFetch, upstreamFor, type ProxyConfig } from "./proxy.ts";
import { LEAD_WINDOW_MS, type LeadInput, type PostPatch, type Store } from "./store.ts";

export interface ApiRequest {
  /** Upper-case. */
  method: string;
  /** "/api/clients" or "/mcp"; no query, no trailing slash. */
  path: string;
  query: URLSearchParams;
  /** Lower-cased names, first value only. */
  headers: Record<string, string | undefined>;
  /** Raw text, "" when there is none. */
  body: string;
}

export interface ApiReply {
  status: number;
  /** JSON-encoded; undefined means an empty body. */
  body?: unknown;
  /** Set only by `/api/chat/:sid/stream` — piped, not buffered. */
  stream?: Response;
  /** Set only by `/api/enter`, which answers with a cookie and a redirect and no body at all. */
  headers?: Record<string, string>;
}

export interface ApiContext {
  /** Opens the store on first call and memoises it for this request. Platform-only routes never call it. */
  store(): Promise<Store>;
  config: ProxyConfig | null;
  /** `VETTA_MCP_TOKEN` — the bearer the platform minted for this app's agents. */
  mcpToken: string | undefined;
  /**
   * `DASHBOARD_TOKEN` — the operator's bearer for every `/api/*` route. Separate from `mcpToken`
   * on purpose: the agents' credential is minted by the platform and is not the operator's.
   */
  dashboardToken: string | undefined;
  /**
   * `DASHBOARD_PASSWORD` — the one credential a person may hold. Generated by the platform next to
   * the token and handed to the operator from the studio's Access panel; `/api/enter` trades it
   * for the same cookie a ticket earns. Unset (every local run) disables the password door.
   */
  dashboardPassword: string | undefined;
  /** `NAIVE_STUDIO_URL` — the studio that installed this app, where a signed-out browser is sent. */
  studioUrl: string | undefined;
  /** `NAIVE_APP_ID` — this app's own `app_…` id, the other half of that studio link. */
  appId: string | undefined;
  /** True on `pnpm serve` / `pnpm dev`. False in the deployed function. */
  local: boolean;
}

/**
 * Every relayed stream opens with this, so the browser's `EventSource` reconnects cheaply when the
 * function hits its duration ceiling instead of backing off to the default three seconds' guesswork.
 */
export const SSE_RETRY = "retry: 3000\n\n";

const NO_ROUTE: ApiReply = { status: 404, body: { error: "no such route" } };
const NOT_ALLOWED: ApiReply = { status: 405, body: { error: "method not allowed" } };
const NOT_CONFIGURED: ApiReply = { status: 503, body: { error: "not configured — set NAIVE_API_KEY" } };
const UNAUTHENTICATED: ApiReply = { status: 401, body: { error: "missing or invalid access token" } };
const CROSS_SITE: ApiReply = { status: 403, body: { error: "cross-site request refused" } };
const NO_GATE: ApiReply = { status: 503, body: { error: "not configured — set DASHBOARD_TOKEN" } };
/** Said to a browser that arrived on its own. There is nothing for it to type; there is a button. */
const CLOSED = "this dashboard is opened from the studio that installed it";
const NO_TICKET: ApiReply = { status: 403, body: { error: `this link did not check out — ${CLOSED}` } };
const NO_PASSWORD: ApiReply = { status: 403, body: { error: "that password did not check out" } };
/** Where a browser lands after `/api/enter`: the operator UI, which the gate screen also owns. */
const DASHBOARD = "/app";
const DENIED = `${DASHBOARD}?entry=denied`;

/**
 * THE OPERATOR'S SESSION, AND WHY IT IS A COOKIE AND NOT A THING THEY HOLD.
 *
 * `DASHBOARD_TOKEN` is generated by the platform (`canonical-spec §29.7`) precisely so that nobody
 * has to invent one — and no route anywhere returns an app secret, so nobody, the operator
 * included, can read it back to paste it. What replaced the paste is one click in the studio:
 * `POST /v1/apps/{id}/entry` mints a short-lived ticket, the browser posts it to `/api/enter`, and
 * that route trades it for the cookie below. The value never passes through the DOM, a URL, storage
 * or anything a person is shown.
 *
 * `HttpOnly` so no script on this page can read it; thirty days because a token that dies with the
 * tab sends the operator back to the studio every morning for a credential neither of them can see.
 *
 * On a deployment the dashboard is also shown INSIDE the studio's cross-site `<iframe>`, and a
 * `SameSite=Lax` cookie is never sent to a framed cross-site document — a framed dashboard could
 * not be signed in at all. So off-laptop the cookie is `SameSite=None; Secure; Partitioned` (CHIPS):
 * sent to the frame, but keyed by the top-level site, so the framed dashboard and the top-level
 * dashboard each sign in once and neither can read the other's jar. What `Lax` used to guard
 * against — another site making the browser spend the cookie on a write — is `sameOrigin` below
 * instead. `pnpm serve` on a laptop keeps `Lax` without `Secure`: `Partitioned` requires `Secure`,
 * and there is no frame to serve.
 */
const COOKIE = "dashboard_session";
const COOKIE_MAX_AGE = 30 * 24 * 60 * 60;
const MUTATING = new Set(["POST", "PUT", "PATCH", "DELETE"]);

/** One cookie out of the header, without a parser dependency and without regex over a whole header. */
function cookieValue(header: string | undefined, name: string): string | undefined {
  for (const part of (header ?? "").split(";")) {
    const at = part.indexOf("=");
    if (at > 0 && part.slice(0, at).trim() === name) return part.slice(at + 1).trim();
  }
  return undefined;
}

/** One field out of a body that is JSON when it parses and a form when it does not. */
function field(body: string, name: string): string {
  try {
    const parsed = JSON.parse(body || "{}") as Record<string, unknown> | null;
    const value = parsed?.[name];
    if (value !== undefined && value !== null) return String(value);
  } catch {
    // Not JSON: the form below.
  }
  return new URLSearchParams(body).get(name) ?? "";
}

/**
 * `POST /api/enter` — the one door through the gate, and the only `/api/*` route that runs before
 * it. It takes a credential that is not the token and answers with a cookie and a redirect and no
 * body: there is nothing here for a person to read, copy or lose. Two credentials open it:
 *
 *   * a **ticket**, minted by the studio (`POST /v1/apps/{id}/entry`) — the automatic path;
 *   * the **password**, `DASHBOARD_PASSWORD`, read off the studio's Access panel and typed into
 *     the gate screen's form — for a browser the studio cannot hand back, or a colleague's.
 *
 * Both earn the identical cookie. A bad or stale ticket, or a wrong password, is refused with no
 * hint which part failed — the difference is a probing oracle. A form (the studio's handoff and
 * the gate screen's own) is sent back to the gate with `entry=denied`, so a person sees a sentence
 * and a way in rather than a JSON body; a JSON caller gets the 403 and the sentence.
 *
 * The form that posts here is served by the studio on a different origin, so this is a cross-site
 * navigation: no CORS applies to it, a cookie may be SET on the way past whatever its `SameSite`,
 * and every request the dashboard makes to its own API afterwards carries it. Being cross-site by
 * design, this route is also the one the same-origin guard in `apiGate` does not ask about.
 */
function enterRoute(req: ApiRequest, ctx: ApiContext): ApiReply {
  if (req.method !== "POST") return NOT_ALLOWED;
  if (!ctx.dashboardToken) return NO_GATE;
  const form = (req.headers["content-type"] ?? "").includes("application/x-www-form-urlencoded");
  const refuse = (why: ApiReply): ApiReply => (form ? { status: 303, headers: { location: DENIED } } : why);
  const password = field(req.body, "password");
  if (password !== "") {
    if (!ctx.dashboardPassword || !sameSecret(password, ctx.dashboardPassword)) return refuse(NO_PASSWORD);
  } else if (!ticketMatches(ctx.dashboardToken, field(req.body, "ticket"), Date.now())) {
    return refuse(NO_TICKET);
  }
  const site = ctx.local ? "SameSite=Lax" : "Secure; SameSite=None; Partitioned";
  return {
    status: 303,
    headers: {
      location: DASHBOARD,
      "set-cookie": `${COOKIE}=${ctx.dashboardToken}; Path=/; HttpOnly; ${site}; Max-Age=${COOKIE_MAX_AGE}`,
    },
  };
}

/**
 * `GET /api/session` — what the gate screen asks before it renders anything: is this browser in,
 * and if not, which doors exist. Ungated, sets nothing, and says nothing a stranger could use: the
 * studio link is the studio's public page, and `password_enabled` is a boolean about a form.
 * `authenticated` is `apiGate`'s own verdict, so the screen and the routes cannot disagree.
 */
function sessionRoute(req: ApiRequest, ctx: ApiContext): ApiReply {
  if (req.method !== "GET") return NOT_ALLOWED;
  const studio = ctx.studioUrl && ctx.appId ? `${ctx.studioUrl.replace(/\/+$/, "")}/apps/${ctx.appId}/open` : null;
  return {
    status: 200,
    body: { authenticated: apiGate(req, ctx) === null, studio_url: studio, password_enabled: Boolean(ctx.dashboardPassword) },
    headers: { "cache-control": "no-store" },
  };
}

/** A malformed body is a validation error, never a 502 — the route below decides which one. */
const parse = (body: string): Record<string, unknown> => {
  try {
    return (JSON.parse(body || "{}") ?? {}) as Record<string, unknown>;
  } catch {
    return {};
  }
};

/** The MCP endpoint: bearer-gated JSON-RPC over POST, on the same document as every `/api/*` row. */
async function mcpRoute(req: ApiRequest, ctx: ApiContext): Promise<ApiReply> {
  // The store opens before the 405 so a bare GET answers 503 while the database is still
  // unreachable: it is what the platform dials to decide the endpoint can serve its tools.
  const store = await ctx.store();
  if (req.method !== "POST") return { status: 405, body: { error: "POST only" } };
  if (!authorized(store, req.headers.authorization, ctx.mcpToken)) {
    return { status: 401, body: { error: "missing or invalid bearer token" } };
  }
  const answer = await handleMcp(req.body, store, ctx.config);
  // A notification has no reply: 202 with no body, as the streamable-HTTP transport asks.
  return answer === null ? { status: 202 } : { status: 200, body: answer };
}

/**
 * Token minting for the Settings screen — **local only**. Minting is unauthenticated (the dashboard
 * has no user auth), so on a public URL it would hand any visitor this app's agent tools. The
 * platform already mints and injects `VETTA_MCP_TOKEN` on the deployment, so nothing is lost there.
 */
async function tokenRoutes(req: ApiRequest, ctx: ApiContext): Promise<ApiReply | null> {
  if (!req.path.startsWith("/api/mcp/tokens")) return null;
  if (!ctx.local) return NO_ROUTE;
  const store = await ctx.store();
  if (req.path === "/api/mcp/tokens") {
    if (req.method === "GET") {
      return { status: 200, body: store.mcpTokens().map(({ id, name, createdAt }) => ({ id, name, createdAt })) };
    }
    if (req.method !== "POST") return NOT_ALLOWED;
    const { name } = parse(req.body) as { name?: string };
    if (!name) return { status: 400, body: { error: "name is required" } };
    return { status: 201, body: mintToken(store, name) };
  }
  const revoke = /^\/api\/mcp\/tokens\/([\w-]+)$/.exec(req.path);
  if (revoke === null) return NO_ROUTE;
  if (req.method !== "DELETE") return NOT_ALLOWED;
  return store.removeMcpToken(revoke[1]!)
    ? { status: 200, body: { ok: true } }
    : { status: 404, body: { error: "no such token" } };
}

/**
 * What an anonymous form may put in the CRM: a bounded number of *open* leads (the store is the one
 * durable thing the deployed entry has — a per-process counter would reset on every cold start), one
 * row per contact-and-domain while it is still a lead, and fields no longer than the form's own.
 * The sales agent working the pipeline (`advance_pipeline`) is what frees the inbox again.
 */
export const OPEN_LEADS_CAP = 200;
const LEAD_FIELD_MAX = 200;
const withinLeadSize = (lead: Partial<LeadInput>): boolean =>
  [lead.name, lead.domain, lead.contact?.name, lead.contact?.email, lead.contact?.role]
    .every((v) => v === undefined || (typeof v === "string" && v.length <= LEAD_FIELD_MAX)) &&
  (lead.note === undefined || (typeof lead.note === "string" && lead.note.length <= 2000)) &&
  (lead.services === undefined || (Array.isArray(lead.services) && lead.services.length <= 10 &&
    lead.services.every((x) => typeof x === "string" && x.length <= LEAD_FIELD_MAX)));

/**
 * The public site's two routes, and the only `/api/*` routes besides `/api/enter` that run before
 * the gate: a visitor holds no bearer. `GET /api/site` is the page's copy — public by definition,
 * cacheable for a minute so a burst of visitors is one read — and `POST /api/leads` is its contact
 * form, which lands as a CRM lead. Neither reads a row a visitor could not already see on the page.
 */
async function publicRoutes(req: ApiRequest, ctx: ApiContext): Promise<ApiReply | null> {
  const { method, path } = req;
  if (path === "/api/site") {
    if (method !== "GET") return NOT_ALLOWED;
    return { status: 200, body: (await ctx.store()).site(), headers: { "cache-control": "public, max-age=60" } };
  }
  if (path === "/api/leads") {
    if (method !== "POST") return NOT_ALLOWED;
    const body = parse(req.body) as Partial<LeadInput>;
    if (!body.name || !body.domain || !body.contact?.name || !body.contact.email) {
      return { status: 400, body: { error: "name, domain and contact {name, email} are required" } };
    }
    if (!withinLeadSize(body)) return { status: 400, body: { error: "a field is longer than the form allows" } };
    const store = await ctx.store();
    const open = store.read().clients.filter((c) => c.stage === "lead");
    const same = (a: string, b: string) => a.trim().toLowerCase() === b.trim().toLowerCase();
    const seen = open.find((c) => same(c.contact.email, body.contact!.email) && same(c.domain, body.domain!));
    if (seen !== undefined) return { status: 200, body: seen };
    if (open.length >= OPEN_LEADS_CAP) {
      return { status: 429, body: { error: "the lead inbox is full — email the agency directly" }, headers: { "retry-after": "86400" } };
    }
    // The cap above bounds how many leads may be open; this bounds how fast the inbox fills. Without
    // it, `OPEN_LEADS_CAP` scripted contact-and-domain pairs shut the form for a day in one burst —
    // no agent turn fires on a lead, so what that costs is business rather than money. An hour's
    // `retry-after`, because unlike a full inbox this clears without anyone doing anything.
    if (!store.admitLead(Date.now())) {
      return {
        status: 429,
        body: { error: "too many leads just now — try again shortly, or email the agency directly" },
        headers: { "retry-after": String(LEAD_WINDOW_MS / 1000) },
      };
    }
    return { status: 201, body: store.createLead(body as LeadInput) };
  }
  return null;
}

/** The store-backed routes: the CRM pipeline and the content queue. */
async function storeRoutes(req: ApiRequest, ctx: ApiContext): Promise<ApiReply | null> {
  const { method, path } = req;

  if (path === "/api/clients") {
    return method === "GET" ? { status: 200, body: (await ctx.store()).read().clients } : NOT_ALLOWED;
  }
  if (path === "/api/posts") {
    return method === "GET" ? { status: 200, body: (await ctx.store()).read().posts } : NOT_ALLOWED;
  }

  const advance = /^\/api\/clients\/([\w-]+)\/advance$/.exec(path);
  if (advance) {
    if (method !== "POST") return NOT_ALLOWED;
    const client = (await ctx.store()).advanceClient(advance[1]!);
    return client ? { status: 200, body: client } : { status: 404, body: { error: "no such client" } };
  }

  const onboard = /^\/api\/clients\/([\w-]+)\/onboard$/.exec(path);
  if (onboard) {
    if (method !== "POST") return NOT_ALLOWED;
    const client = (await ctx.store()).onboardClient(onboard[1]!);
    if (!client) return { status: 404, body: { error: "no such client" } };
    if (client.stage !== "active") return { status: 409, body: { error: "a churned client cannot be onboarded" } };
    // With a key present, fan out the client's crew on the platform; without one the store move
    // still lands, so the pipeline works before the key does.
    const agents = ctx.config === null ? null : await provisionClientAgents(ctx.config, client.slug);
    return { status: 200, body: { client, agents } };
  }

  const postNow = /^\/api\/posts\/([\w-]+)\/post-now$/.exec(path);
  if (postNow) {
    if (method !== "POST") return NOT_ALLOWED;
    const store = await ctx.store();
    const post = store.read().posts.find((p) => p.id === postNow[1]);
    if (!post) return { status: 404, body: { error: "no such post" } };
    // When the platform is configured, publish for real before marking posted.
    const upstream = ctx.config === null ? null : upstreamFor("POST", "/api/social/posts", ctx.config.identityId);
    if (ctx.config !== null && upstream !== null) {
      const published = await proxyFetch(ctx.config, upstream, JSON.stringify({
        content: post.summary, title: post.title, platforms: [post.channel],
      }));
      if (!published.ok) return { status: 502, body: { error: "publish failed" } };
    }
    return { status: 200, body: store.updatePost(post.id, { status: "posted" }) };
  }

  const patch = /^\/api\/posts\/([\w-]+)$/.exec(path);
  if (patch) {
    if (method !== "PATCH") return NOT_ALLOWED;
    const body = parse(req.body) as PostPatch;
    if (!body.status && !body.scheduledFor) return { status: 400, body: { error: "status or scheduledFor is required" } };
    const updated = (await ctx.store()).updatePost(patch[1]!, {
      status: body.status, rejectedReason: body.rejectedReason, scheduledFor: body.scheduledFor,
    });
    return updated ? { status: 200, body: updated } : { status: 404, body: { error: "no such post" } };
  }

  return null;
}

/** Resolved once per instance: the agent the agency chat talks to. */
let chatAgent: string | null = null;
async function chatAgentId(config: ProxyConfig): Promise<string | null> {
  if (chatAgent !== null) return chatAgent;
  // The whole roster: `client-manager` is one row among an agency's hundreds, and resolving it over
  // page one alone answered "no client-manager agent in this organization" for an org that has one.
  const roster = await listAgents(config);
  if (roster === null) return null;
  chatAgent = roster.find((a) => a.name === "client-manager")?.id ?? null;
  return chatAgent;
}

/**
 * Everything that needs the org's key: chat, the agent roster, an agent's spend, the sessions
 * behind the approval queue and the agent history, the client's social accounts, the timers, and
 * this project's context (the setup answers) from its latest applied install.
 */
const PLATFORM_ROUTE = /^\/api\/(chat|agents|social|sessions|deployments|context)(\/|$)/;

async function platformRoutes(req: ApiRequest, ctx: ApiContext): Promise<ApiReply> {
  if (!PLATFORM_ROUTE.test(req.path)) return NO_ROUTE;
  const config = ctx.config;
  if (config === null) return NOT_CONFIGURED;
  try {
    if (req.method === "POST" && req.path === "/api/chat") {
      const agent = await chatAgentId(config);
      if (agent === null) return { status: 503, body: { error: "no client-manager agent in this organization" } };
      const message = parse(req.body).message;
      const created = await proxyFetch(config, { method: "POST", path: "/v1/sessions" },
        JSON.stringify({ agent_id: agent, message: typeof message === "string" ? message : "" }));
      return { status: created.status, body: await created.json() };
    }
    if (req.method === "GET" && (req.path === "/api/agents" || req.path === "/api/deployments")) {
      // Assembled here rather than relayed: the upstream pages at 20, so the screen that lists the
      // agency's own agents was showing whichever twenty came first — never `sales`, on a real org;
      // and a timer past the first hundred read as an agent with none.
      const rows = await collect(config, req.path === "/api/agents" ? "/v1/agents" : "/v1/deployments");
      if (rows === null) return { status: 502, body: { error: "upstream unavailable" } };
      return { status: 200, body: { data: rows, has_more: false, next_cursor: null } };
    }
    if (req.method === "GET" && req.path === "/api/context") {
      const found = await latestContext(config);
      if (found === null) return { status: 502, body: { error: "upstream unavailable" } };
      return found.context === null
        ? { status: 404, body: { error: "no applied install for this project" } }
        : { status: 200, body: found };
    }
    const upstream = upstreamFor(req.method, req.path, config.identityId, req.query);
    if (upstream === null) return NO_ROUTE;
    const answer = await proxyFetch(config, upstream, req.method === "GET" ? null : req.body || "{}");
    if (upstream.sse) return { status: answer.status, stream: answer };
    return { status: answer.status, body: await answer.json() };
  } catch {
    return { status: 502, body: { error: "upstream unavailable" } };
  }
}

/**
 * The one thing allowed to stand in for the operator's token, and the whole of what `ctx.local`
 * may be built from: a caller on the loopback interface.
 *
 * `createServer().listen(port)` binds *every* interface, so "the local server answered it" is not
 * the same fact as "the request came from this machine" — a peer on the LAN, or anything pointed
 * through a tunnel, is neither. Taken from the socket, never from a header or a proxy hop, because
 * everything a caller can write is a claim rather than a fact. The deployed entry calls none of
 * this: it hard-codes `local: false`.
 */
export const isLoopback = (remoteAddress: string | undefined): boolean =>
  remoteAddress === "127.0.0.1" || remoteAddress === "::1" || remoteAddress === "::ffff:127.0.0.1";

/**
 * The gate on the whole `/api/*` surface: `Authorization: Bearer <DASHBOARD_TOKEN>`, compared in
 * constant time. Null admits the request; anything else is the reply.
 *
 * Without it the deployment is a public URL that hands anyone who finds it the CRM (client names,
 * domains, contacts and their email addresses), the org's agent roster with its system prompts,
 * the content queue as a *writable* surface, and the relay of any session in the organization.
 *
 * Two rules it never bends:
 *   * **Fail closed.** No token configured on a deployment is 503, never open. A missing credential
 *     must never mean "let everyone in" — that is precisely the bug being fixed.
 *   * **Local means local.** `pnpm serve` with nothing set stays usable, and `ctx.local` comes from
 *     `isLoopback` on the request's own socket; the deployed entry hard-codes it false, so no
 *     header, host or proxy hop a caller controls can claim it.
 *
 * `/mcp` never reaches here: the agents' bearer is its own credential and is unchanged.
 */
function apiGate(req: ApiRequest, ctx: ApiContext): ApiReply | null {
  if (!ctx.dashboardToken) return ctx.local ? null : NO_GATE;
  // The cookie `/api/enter` set, first: it is how a browser that was never given a token gets in.
  const held = cookieValue(req.headers.cookie, COOKIE);
  if (held !== undefined) {
    if (!sameSecret(held, ctx.dashboardToken)) return UNAUTHENTICATED;
    return MUTATING.has(req.method) && !sameOrigin(req) ? CROSS_SITE : null;
  }
  const token = bearerOf(req.headers.authorization);
  return token !== null && sameSecret(token, ctx.dashboardToken) ? null : UNAUTHENTICATED;
}

/**
 * Whether a request the browser attached the cookie to came from this dashboard's own pages. A
 * `SameSite=None` cookie rides on cross-site requests too, so a cookie-authenticated WRITE must
 * show it was not another site's doing: `sec-fetch-site` (which the browser sets and a page cannot
 * forge) says `same-origin`, or `none` for the address bar; a browser too old to send it must at
 * least send an `origin` that is this host. Reads, bearers and `/api/enter` are not asked — the
 * studio's ticket form is cross-site by design, and a bearer was never in a cookie jar.
 */
function sameOrigin(req: ApiRequest): boolean {
  const site = req.headers["sec-fetch-site"];
  if (site !== undefined) return site === "same-origin" || site === "none";
  const origin = req.headers.origin;
  if (origin === undefined || req.headers.host === undefined) return false;
  try {
    return new URL(origin).host === req.headers.host;
  } catch {
    return false;
  }
}

/** The whole route table, in order: `/mcp`, the door, the public site, the gate, the local token routes, the store, the platform. */
export async function handleRequest(req: ApiRequest, ctx: ApiContext): Promise<ApiReply> {
  if (req.path === "/mcp") return mcpRoute(req, ctx);
  if (!req.path.startsWith("/api/")) return NO_ROUTE;
  // The two routes that must run before the gate: the one that gets a browser through it, and the
  // one that tells the browser whether it is.
  if (req.path === "/api/enter") return enterRoute(req, ctx);
  if (req.path === "/api/session") return sessionRoute(req, ctx);
  // The public site's own two routes: a visitor holds no bearer.
  const open = await publicRoutes(req, ctx);
  if (open !== null) return open;
  // Before the route table, so an unauthenticated caller cannot even map which routes exist.
  const denied = apiGate(req, ctx);
  if (denied !== null) return denied;
  return (await tokenRoutes(req, ctx)) ?? (await storeRoutes(req, ctx)) ?? platformRoutes(req, ctx);
}
